name: CI
run-name: ${{ github.actor }} is testing out GitHub Actions

env: 
  GITHUB_ACTIONS: true

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  github-task-job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Show GITHUB_ACTIONS environment variable
        run: echo $GITHUB_ACTIONS

      - name: Show event name
        run: echo "The job was triggered by a ${{ github.event_name }} event"

      - name: Show branch and repository
        run: echo "Name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}"

